P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Models/Estagio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EstagiosDEIS.Models
{
    [Table("Estagios")]

    public class Estagio
    {
        [Key]
        public int estagioId { get; set; }

        [ForeignKey("Aluna")]
        public int AlunaId { get; set; }

        [ForeignKey("Docente")]
        public int DocenteId { get; set; }    //orientador de estágio 

        [ForeignKey("Empresa")]
        public int EmpresaId { get; set; }

        [ForeignKey("Proposta")]
        public int PropostaId { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public DateTime dataInicio { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public DateTime dataFim { get; set; }
        
        [Range(0, 20, ErrorMessage = "Nota tem de ser de 0 a 20")]
        public double avaliacao_Empresa { get; set; }
        [Range(0, 20, ErrorMessage = "Nota tem de ser de 0 a 20")]
        public double avaliacao_Aluno { get; set; }

        public  Proposta Proposta { get; set; }
        public  Aluna Aluna { get; set; } 
        public Docente Docente { get; set; }
        public  Empresa Empresa { get; set; }
    }
}

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Controllers/DefesasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EstagiosDEIS.Models;

namespace EstagiosDEIS.Controllers
{[Authorize]
    public class DefesasController : Controller
    {
        private EstagiosContext db = new EstagiosContext();

        // GET: Defesas
        public ActionResult Index()
        {
            var defesas = db.Defesas.Include(d => d.Estagio);
            return View(defesas.ToList());
        }

        public ActionResult ListaDefesas()
        {
            var defesas = db.Defesas.Include(d => d.Estagio);
            return View(defesas.ToList());
        }

        // GET: Defesas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Defesa defesa = db.Defesas.Find(id);
            if (defesa == null)
            {
                return HttpNotFound();
            }
            return View(defesa);
        }

        // GET: Defesas/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Estagio estagio = db.Estagios.Find(id);


            if (estagio == null)
                return HttpNotFound();
            return View();
        }

        // POST: Defesas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "defesaId,EstagioId,Data_Defesa,avaliacao_Aluno")] Defesa defesa,int id)
        {
            Estagio estagio = db.Estagios.Find(id);

            defesa.EstagioId = estagio.estagioId;
            if (ModelState.IsValid)
            {
                db.Defesas.Add(defesa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(defesa);
        }

        // GET: Defesas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Defesa defesa = db.Defesas.Find(id);
            if (defesa == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstagioId = new SelectList(db.Estagios, "estagioId", "estagioId", defesa.EstagioId);
            return View(defesa);
        }

        // POST: Defesas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "defesaId,EstagioId,Data_Defesa,avaliacao_Aluno")] Defesa defesa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(defesa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EstagioId = new SelectList(db.Estagios, "estagioId", "estagioId", defesa.EstagioId);
            return View(defesa);
        }

        // GET: Defesas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Defesa defesa = db.Defesas.Find(id);
            if (defesa == null)
            {
                return HttpNotFound();
            }
            return View(defesa);
        }

        // POST: Defesas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Defesa defesa = db.Defesas.Find(id);
            db.Defesas.Remove(defesa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult DefinirDataDefesa(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Defesa defesa = db.Defesas.Find(id);
            if (defesa == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstagioId = new SelectList(db.Estagios, "estagioId", "estagioId", defesa.EstagioId);
            return View(defesa);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DefinirDataDefesa([Bind(Include = "defesaId,EstagioId,Data_Defesa,avaliacao_Aluno")] Defesa defesa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(defesa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EstagioId = new SelectList(db.Estagios, "estagioId", "estagioId", defesa.EstagioId);
            return View(defesa);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Controllers/EstagiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EstagiosDEIS.Models;
using Microsoft.AspNet.Identity;

namespace EstagiosDEIS.Controllers
{[Authorize]
    public class EstagiosController : Controller
    {
        private EstagiosContext db = new EstagiosContext();
        public ActionResult TotalEstagios(Estagio estagio)
        {
            var numeroEstagios = (from t in db.Estagios
                                  where t.dataFim != null
                                  orderby t.dataFim.Year
                                  select t).Count();


            return View(numeroEstagios);

        }
        // GET: Estagios
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();

            if (User.IsInRole("Docente") || User.IsInRole("Comissao"))
            {
                var docente = db.Docentes.SingleOrDefault(x => x.UserId.Equals(userId));


                return View(db.Estagios.Where(c => c.DocenteId== docente.docenteId).ToList());
            }
            else
            {
                var estagios = db.Estagios.Include(e => e.Aluna).Include(e => e.Docente).Include(e => e.Empresa).Include(e => e.Proposta);
                return View(estagios.ToList());
            }
        }

        // GET: Estagios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estagio estagio = db.Estagios.Find(id);
            if (estagio == null)
            {
                return HttpNotFound();
            }
            return View(estagio);
        }

        // GET: Estagios/Create
        public ActionResult Create(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidatura candidatura = db.Candidaturas.Find(id);


            if (candidatura == null)
                return HttpNotFound();
         

           
            ViewBag.DocenteId = new SelectList(db.Docentes, "docenteId", "Nome");
           
             return View();
        }

        // POST: Estagios/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "estagioId,AlunaId,DocenteId,EmpresaId,PropostaId,dataInicio,dataFim,avaliacao_Empresa,avaliacao_Aluno")] Estagio estagio,int id)
        {

            
            Candidatura candidatura = db.Candidaturas.Find(id);


            /*Para obter o id da proposta, do aluno e da empresa. Só é necessario escolher o docente que vai orientar o estágio*/
            Proposta proposta = db.Propostas.Find(candidatura.PropostaId);
            Aluna aluna = db.Alunas.Find(candidatura.AlunaId);
            Empresa empresa = db.Empresas.Find(proposta.EmpresaId);



            estagio.AlunaId = aluna.alunoId;
            estagio.PropostaId = proposta.propostaId;
            estagio.EmpresaId = empresa.empresaId;


            ViewBag.DocenteId = new SelectList(db.Docentes, "docenteId", "Nome", estagio.DocenteId);

            if (ModelState.IsValid)
            {
                db.Estagios.Add(estagio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(estagio);
        }

        // GET: Estagios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estagio estagio = db.Estagios.Find(id);
            if (estagio == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlunaId = new SelectList(db.Alunas, "alunoId", "Nome", estagio.AlunaId);
            ViewBag.DocenteId = new SelectList(db.Docentes, "docenteId", "Nome", estagio.DocenteId);
            ViewBag.EmpresaId = new SelectList(db.Empresas, "empresaId", "Nome", estagio.EmpresaId);
            ViewBag.PropostaId = new SelectList(db.Propostas, "propostaId", "propostaId", estagio.PropostaId);
            return View(estagio);
        }

        // POST: Estagios/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "estagioId,AlunaId,DocenteId,EmpresaId,PropostaId,dataInicio,dataFim,avaliacao_Empresa,avaliacao_Aluno")] Estagio estagio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estagio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AlunaId = new SelectList(db.Alunas, "alunoId", "Nome", estagio.AlunaId);
            ViewBag.DocenteId = new SelectList(db.Docentes, "docenteId", "Nome", estagio.DocenteId);
            ViewBag.EmpresaId = new SelectList(db.Empresas, "empresaId", "Nome", estagio.EmpresaId);
            ViewBag.PropostaId = new SelectList(db.Propostas, "propostaId", "propostaId", estagio.PropostaId);
            return View(estagio);
        }

        // GET: Estagios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estagio estagio = db.Estagios.Find(id);
            if (estagio == null)
            {
                return HttpNotFound();
            }
            return View(estagio);
        }

        // POST: Estagios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estagio estagio = db.Estagios.Find(id);
            db.Estagios.Remove(estagio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AvaliarAluno(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estagio estagio = db.Estagios.Find(id);
            if (estagio == null)
            {
                return HttpNotFound();
            }

            if (DateTime.Now < estagio.dataFim)
            {
                return View("Erro");
            }

            return View(estagio);
        }
        [HttpPost]
        public ActionResult AvaliarAluno([Bind(Include = "estagioId,AlunaId,DocenteId,EmpresaId,PropostaId,dataInicio,dataFim,avaliacao_Empresa,avaliacao_Aluno")]Estagio estagio,int id)
        {
            Estagio E = db.Estagios.Find(id);

            

            if (ModelState.IsValid)
            {
                db.Entry(estagio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estagio);
        }



        /*View de erro, para quando o estágio ainda não chegou ao fim*/
        public ActionResult Erro()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Views/Estagios/AvaliarAluno.cshtml
@model EstagiosDEIS.Models.Estagio

@{
    ViewBag.Title = "AvaliarAluno";
}

<h2>AvaliarAluno</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Estagio</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.AlunaId)
    @Html.HiddenFor(model => model.avaliacao_Empresa)
    @Html.HiddenFor(model => model.dataFim)
    @Html.HiddenFor(model => model.dataInicio)
    @Html.HiddenFor(model => model.DocenteId)
    @Html.HiddenFor(model => model.EmpresaId)
    @Html.HiddenFor(model => model.estagioId)
    @Html.HiddenFor(model => model.PropostaId)
    
    <div class="form-group">
        @Html.LabelFor(model => model.avaliacao_Aluno, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.avaliacao_Aluno, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.avaliacao_Aluno, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Avaliar o Aluno" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Avaliar Aluno", "Index")
</div>

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Views/Estagios/Create.cshtml
@model EstagiosDEIS.Models.Estagio

@{
    ViewBag.Title = "Associar Estagio";
}

<h2>Associar Estágio</h2>

<div align="right" class="jumbotron" style="background: #0094ff">
    <img align="top" src="~/Content/imagens/associarEstagio.png" />

</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Estagio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.DocenteId, "Associar orientador a estágio: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DocenteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DocenteId, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            @Html.LabelFor(model => model.dataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dataInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataFim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataFim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dataFim, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Associar Estágio a aluno" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Views/Estagios/Delete.cshtml
@model EstagiosDEIS.Models.Estagio

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estagio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aluna.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aluna.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Docente.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Docente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proposta.objetivos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proposta.objetivos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataFim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataFim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avaliacao_Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avaliacao_Empresa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Views/Estagios/Details.cshtml
@model EstagiosDEIS.Models.Estagio

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Estagio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aluna.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aluna.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Docente.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Docente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proposta.objetivos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proposta.objetivos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dataFim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dataFim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avaliacao_Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avaliacao_Empresa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.estagioId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Views/Estagios/Edit.cshtml
@model EstagiosDEIS.Models.Estagio

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estagio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.estagioId)

        <div class="form-group">
            @Html.LabelFor(model => model.AlunaId, "AlunaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlunaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlunaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocenteId, "DocenteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DocenteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DocenteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpresaId, "EmpresaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpresaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpresaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropostaId, "PropostaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PropostaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PropostaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dataInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataFim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dataFim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dataFim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.avaliacao_Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.avaliacao_Empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.avaliacao_Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

P4_21250157_SoraiaTarrinha/EstagiosDEIS/EstagiosDEIS/Views/Estagios/Index.cshtml
@model IEnumerable<EstagiosDEIS.Models.Estagio>

@{
    ViewBag.Title = "Estágios";
}


<h2>Lista de Estágios</h2>
<div align="right" class="jumbotron" style="background: #ffd800">
    <img align="top" src="~/Content/imagens/estagio.png" />

</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Aluna.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Docente.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empresa.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Proposta.propostaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dataInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dataFim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.avaliacao_Empresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.avaliacao_Aluno)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Aluna.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Docente.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empresa.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proposta.propostaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dataInicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dataFim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.avaliacao_Empresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.avaliacao_Aluno)
        </td>
        <td>
            @Html.ActionLink("Avaliar Aluno", "AvaliarAluno", new { id = item.estagioId })|
            @Html.ActionLink("Edit", "Edit", new { id = item.estagioId }) |
            @Html.ActionLink("Details", "Details", new { id = item.estagioId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.estagioId })|
            @Html.ActionLink("Atribuir Defesa", "Create", "Defesas", new { id = item.estagioId }, null)|

        </td>
    </tr>
    }

</table>